# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='device.proto',
  package='arhat',
  syntax='proto3',
  serialized_options=b'Z\037arhat.dev/arhat-proto/arhatgopb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x64\x65vice.proto\x12\x05\x61rhat\"\xc0\x01\n\tTLSConfig\x12\x13\n\x0bserver_name\x18\x01 \x01(\t\x12\x1c\n\x14insecure_skip_verify\x18\x02 \x01(\x08\x12\x13\n\x0bmin_version\x18\x03 \x01(\r\x12\x13\n\x0bmax_version\x18\x04 \x01(\r\x12\x0f\n\x07\x63\x61_cert\x18\x05 \x01(\x0c\x12\x0c\n\x04\x63\x65rt\x18\x06 \x01(\x0c\x12\x0b\n\x03key\x18\x07 \x01(\x0c\x12\x15\n\rcipher_suites\x18\x08 \x03(\r\x12\x13\n\x0bnext_protos\x18\t \x03(\t\"\xa5\x01\n\x10\x44\x65viceConnectCmd\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x33\n\x06params\x18\x02 \x03(\x0b\x32#.arhat.DeviceConnectCmd.ParamsEntry\x12\x1d\n\x03tls\x18\x03 \x01(\x0b\x32\x10.arhat.TLSConfig\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x84\x01\n\x10\x44\x65viceOperateCmd\x12\x33\n\x06params\x18\x01 \x03(\x0b\x32#.arhat.DeviceOperateCmd.ParamsEntry\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x84\x01\n\x17\x44\x65viceMetricsCollectCmd\x12:\n\x06params\x18\x01 \x03(\x0b\x32*.arhat.DeviceMetricsCollectCmd.ParamsEntry\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x10\n\x0e\x44\x65viceCloseCmd\"*\n\x18\x44\x65viceOperationResultMsg\x12\x0e\n\x06result\x18\x01 \x03(\x0c\"l\n\x10\x44\x65viceMetricsMsg\x12-\n\x06values\x18\x01 \x03(\x0b\x32\x1d.arhat.DeviceMetricsMsg.Value\x1a)\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"6\n\x0e\x44\x65viceEventMsg\x12$\n\x04kind\x18\x01 \x01(\x0e\x32\x16.arhat.DeviceEventType*)\n\x0f\x44\x65viceEventType\x12\x16\n\x12_INVALID_DEV_EVENT\x10\x00\x42!Z\x1f\x61rhat.dev/arhat-proto/arhatgopbb\x06proto3'
)

_DEVICEEVENTTYPE = _descriptor.EnumDescriptor(
  name='DeviceEventType',
  full_name='arhat.DeviceEventType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='_INVALID_DEV_EVENT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=884,
  serialized_end=925,
)
_sym_db.RegisterEnumDescriptor(_DEVICEEVENTTYPE)

DeviceEventType = enum_type_wrapper.EnumTypeWrapper(_DEVICEEVENTTYPE)
_INVALID_DEV_EVENT = 0



_TLSCONFIG = _descriptor.Descriptor(
  name='TLSConfig',
  full_name='arhat.TLSConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_name', full_name='arhat.TLSConfig.server_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='insecure_skip_verify', full_name='arhat.TLSConfig.insecure_skip_verify', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_version', full_name='arhat.TLSConfig.min_version', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_version', full_name='arhat.TLSConfig.max_version', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ca_cert', full_name='arhat.TLSConfig.ca_cert', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cert', full_name='arhat.TLSConfig.cert', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='arhat.TLSConfig.key', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cipher_suites', full_name='arhat.TLSConfig.cipher_suites', index=7,
      number=8, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='next_protos', full_name='arhat.TLSConfig.next_protos', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=216,
)


_DEVICECONNECTCMD_PARAMSENTRY = _descriptor.Descriptor(
  name='ParamsEntry',
  full_name='arhat.DeviceConnectCmd.ParamsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='arhat.DeviceConnectCmd.ParamsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='arhat.DeviceConnectCmd.ParamsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=384,
)

_DEVICECONNECTCMD = _descriptor.Descriptor(
  name='DeviceConnectCmd',
  full_name='arhat.DeviceConnectCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='arhat.DeviceConnectCmd.target', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='arhat.DeviceConnectCmd.params', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tls', full_name='arhat.DeviceConnectCmd.tls', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DEVICECONNECTCMD_PARAMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=384,
)


_DEVICEOPERATECMD_PARAMSENTRY = _descriptor.Descriptor(
  name='ParamsEntry',
  full_name='arhat.DeviceOperateCmd.ParamsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='arhat.DeviceOperateCmd.ParamsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='arhat.DeviceOperateCmd.ParamsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=384,
)

_DEVICEOPERATECMD = _descriptor.Descriptor(
  name='DeviceOperateCmd',
  full_name='arhat.DeviceOperateCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='arhat.DeviceOperateCmd.params', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='arhat.DeviceOperateCmd.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DEVICEOPERATECMD_PARAMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=519,
)


_DEVICEMETRICSCOLLECTCMD_PARAMSENTRY = _descriptor.Descriptor(
  name='ParamsEntry',
  full_name='arhat.DeviceMetricsCollectCmd.ParamsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='arhat.DeviceMetricsCollectCmd.ParamsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='arhat.DeviceMetricsCollectCmd.ParamsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=384,
)

_DEVICEMETRICSCOLLECTCMD = _descriptor.Descriptor(
  name='DeviceMetricsCollectCmd',
  full_name='arhat.DeviceMetricsCollectCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='arhat.DeviceMetricsCollectCmd.params', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DEVICEMETRICSCOLLECTCMD_PARAMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=522,
  serialized_end=654,
)


_DEVICECLOSECMD = _descriptor.Descriptor(
  name='DeviceCloseCmd',
  full_name='arhat.DeviceCloseCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=656,
  serialized_end=672,
)


_DEVICEOPERATIONRESULTMSG = _descriptor.Descriptor(
  name='DeviceOperationResultMsg',
  full_name='arhat.DeviceOperationResultMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='arhat.DeviceOperationResultMsg.result', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=674,
  serialized_end=716,
)


_DEVICEMETRICSMSG_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='arhat.DeviceMetricsMsg.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='arhat.DeviceMetricsMsg.Value.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='arhat.DeviceMetricsMsg.Value.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=785,
  serialized_end=826,
)

_DEVICEMETRICSMSG = _descriptor.Descriptor(
  name='DeviceMetricsMsg',
  full_name='arhat.DeviceMetricsMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='arhat.DeviceMetricsMsg.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DEVICEMETRICSMSG_VALUE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=718,
  serialized_end=826,
)


_DEVICEEVENTMSG = _descriptor.Descriptor(
  name='DeviceEventMsg',
  full_name='arhat.DeviceEventMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kind', full_name='arhat.DeviceEventMsg.kind', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=828,
  serialized_end=882,
)

_DEVICECONNECTCMD_PARAMSENTRY.containing_type = _DEVICECONNECTCMD
_DEVICECONNECTCMD.fields_by_name['params'].message_type = _DEVICECONNECTCMD_PARAMSENTRY
_DEVICECONNECTCMD.fields_by_name['tls'].message_type = _TLSCONFIG
_DEVICEOPERATECMD_PARAMSENTRY.containing_type = _DEVICEOPERATECMD
_DEVICEOPERATECMD.fields_by_name['params'].message_type = _DEVICEOPERATECMD_PARAMSENTRY
_DEVICEMETRICSCOLLECTCMD_PARAMSENTRY.containing_type = _DEVICEMETRICSCOLLECTCMD
_DEVICEMETRICSCOLLECTCMD.fields_by_name['params'].message_type = _DEVICEMETRICSCOLLECTCMD_PARAMSENTRY
_DEVICEMETRICSMSG_VALUE.containing_type = _DEVICEMETRICSMSG
_DEVICEMETRICSMSG.fields_by_name['values'].message_type = _DEVICEMETRICSMSG_VALUE
_DEVICEEVENTMSG.fields_by_name['kind'].enum_type = _DEVICEEVENTTYPE
DESCRIPTOR.message_types_by_name['TLSConfig'] = _TLSCONFIG
DESCRIPTOR.message_types_by_name['DeviceConnectCmd'] = _DEVICECONNECTCMD
DESCRIPTOR.message_types_by_name['DeviceOperateCmd'] = _DEVICEOPERATECMD
DESCRIPTOR.message_types_by_name['DeviceMetricsCollectCmd'] = _DEVICEMETRICSCOLLECTCMD
DESCRIPTOR.message_types_by_name['DeviceCloseCmd'] = _DEVICECLOSECMD
DESCRIPTOR.message_types_by_name['DeviceOperationResultMsg'] = _DEVICEOPERATIONRESULTMSG
DESCRIPTOR.message_types_by_name['DeviceMetricsMsg'] = _DEVICEMETRICSMSG
DESCRIPTOR.message_types_by_name['DeviceEventMsg'] = _DEVICEEVENTMSG
DESCRIPTOR.enum_types_by_name['DeviceEventType'] = _DEVICEEVENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TLSConfig = _reflection.GeneratedProtocolMessageType('TLSConfig', (_message.Message,), {
  'DESCRIPTOR' : _TLSCONFIG,
  '__module__' : 'device_pb2'
  # @@protoc_insertion_point(class_scope:arhat.TLSConfig)
  })
_sym_db.RegisterMessage(TLSConfig)

DeviceConnectCmd = _reflection.GeneratedProtocolMessageType('DeviceConnectCmd', (_message.Message,), {

  'ParamsEntry' : _reflection.GeneratedProtocolMessageType('ParamsEntry', (_message.Message,), {
    'DESCRIPTOR' : _DEVICECONNECTCMD_PARAMSENTRY,
    '__module__' : 'device_pb2'
    # @@protoc_insertion_point(class_scope:arhat.DeviceConnectCmd.ParamsEntry)
    })
  ,
  'DESCRIPTOR' : _DEVICECONNECTCMD,
  '__module__' : 'device_pb2'
  # @@protoc_insertion_point(class_scope:arhat.DeviceConnectCmd)
  })
_sym_db.RegisterMessage(DeviceConnectCmd)
_sym_db.RegisterMessage(DeviceConnectCmd.ParamsEntry)

DeviceOperateCmd = _reflection.GeneratedProtocolMessageType('DeviceOperateCmd', (_message.Message,), {

  'ParamsEntry' : _reflection.GeneratedProtocolMessageType('ParamsEntry', (_message.Message,), {
    'DESCRIPTOR' : _DEVICEOPERATECMD_PARAMSENTRY,
    '__module__' : 'device_pb2'
    # @@protoc_insertion_point(class_scope:arhat.DeviceOperateCmd.ParamsEntry)
    })
  ,
  'DESCRIPTOR' : _DEVICEOPERATECMD,
  '__module__' : 'device_pb2'
  # @@protoc_insertion_point(class_scope:arhat.DeviceOperateCmd)
  })
_sym_db.RegisterMessage(DeviceOperateCmd)
_sym_db.RegisterMessage(DeviceOperateCmd.ParamsEntry)

DeviceMetricsCollectCmd = _reflection.GeneratedProtocolMessageType('DeviceMetricsCollectCmd', (_message.Message,), {

  'ParamsEntry' : _reflection.GeneratedProtocolMessageType('ParamsEntry', (_message.Message,), {
    'DESCRIPTOR' : _DEVICEMETRICSCOLLECTCMD_PARAMSENTRY,
    '__module__' : 'device_pb2'
    # @@protoc_insertion_point(class_scope:arhat.DeviceMetricsCollectCmd.ParamsEntry)
    })
  ,
  'DESCRIPTOR' : _DEVICEMETRICSCOLLECTCMD,
  '__module__' : 'device_pb2'
  # @@protoc_insertion_point(class_scope:arhat.DeviceMetricsCollectCmd)
  })
_sym_db.RegisterMessage(DeviceMetricsCollectCmd)
_sym_db.RegisterMessage(DeviceMetricsCollectCmd.ParamsEntry)

DeviceCloseCmd = _reflection.GeneratedProtocolMessageType('DeviceCloseCmd', (_message.Message,), {
  'DESCRIPTOR' : _DEVICECLOSECMD,
  '__module__' : 'device_pb2'
  # @@protoc_insertion_point(class_scope:arhat.DeviceCloseCmd)
  })
_sym_db.RegisterMessage(DeviceCloseCmd)

DeviceOperationResultMsg = _reflection.GeneratedProtocolMessageType('DeviceOperationResultMsg', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEOPERATIONRESULTMSG,
  '__module__' : 'device_pb2'
  # @@protoc_insertion_point(class_scope:arhat.DeviceOperationResultMsg)
  })
_sym_db.RegisterMessage(DeviceOperationResultMsg)

DeviceMetricsMsg = _reflection.GeneratedProtocolMessageType('DeviceMetricsMsg', (_message.Message,), {

  'Value' : _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
    'DESCRIPTOR' : _DEVICEMETRICSMSG_VALUE,
    '__module__' : 'device_pb2'
    # @@protoc_insertion_point(class_scope:arhat.DeviceMetricsMsg.Value)
    })
  ,
  'DESCRIPTOR' : _DEVICEMETRICSMSG,
  '__module__' : 'device_pb2'
  # @@protoc_insertion_point(class_scope:arhat.DeviceMetricsMsg)
  })
_sym_db.RegisterMessage(DeviceMetricsMsg)
_sym_db.RegisterMessage(DeviceMetricsMsg.Value)

DeviceEventMsg = _reflection.GeneratedProtocolMessageType('DeviceEventMsg', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEEVENTMSG,
  '__module__' : 'device_pb2'
  # @@protoc_insertion_point(class_scope:arhat.DeviceEventMsg)
  })
_sym_db.RegisterMessage(DeviceEventMsg)


DESCRIPTOR._options = None
_DEVICECONNECTCMD_PARAMSENTRY._options = None
_DEVICEOPERATECMD_PARAMSENTRY._options = None
_DEVICEMETRICSCOLLECTCMD_PARAMSENTRY._options = None
# @@protoc_insertion_point(module_scope)
