# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peripheral.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='peripheral.proto',
  package='arhat',
  syntax='proto3',
  serialized_options=b'Z\037arhat.dev/arhat-proto/arhatgopb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10peripheral.proto\x12\x05\x61rhat\"\xc0\x01\n\tTLSConfig\x12\x13\n\x0bserver_name\x18\x01 \x01(\t\x12\x1c\n\x14insecure_skip_verify\x18\x02 \x01(\x08\x12\x13\n\x0bmin_version\x18\x03 \x01(\r\x12\x13\n\x0bmax_version\x18\x04 \x01(\r\x12\x0f\n\x07\x63\x61_cert\x18\x05 \x01(\x0c\x12\x0c\n\x04\x63\x65rt\x18\x06 \x01(\x0c\x12\x0b\n\x03key\x18\x07 \x01(\x0c\x12\x15\n\rcipher_suites\x18\x08 \x03(\r\x12\x13\n\x0bnext_protos\x18\t \x03(\t\"\xad\x01\n\x14PeripheralConnectCmd\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x37\n\x06params\x18\x02 \x03(\x0b\x32\'.arhat.PeripheralConnectCmd.ParamsEntry\x12\x1d\n\x03tls\x18\x03 \x01(\x0b\x32\x10.arhat.TLSConfig\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8c\x01\n\x14PeripheralOperateCmd\x12\x37\n\x06params\x18\x01 \x03(\x0b\x32\'.arhat.PeripheralOperateCmd.ParamsEntry\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8c\x01\n\x1bPeripheralMetricsCollectCmd\x12>\n\x06params\x18\x01 \x03(\x0b\x32..arhat.PeripheralMetricsCollectCmd.ParamsEntry\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x14\n\x12PeripheralCloseCmd\".\n\x1cPeripheralOperationResultMsg\x12\x0e\n\x06result\x18\x01 \x03(\x0c\"t\n\x14PeripheralMetricsMsg\x12\x31\n\x06values\x18\x01 \x03(\x0b\x32!.arhat.PeripheralMetricsMsg.Value\x1a)\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\">\n\x12PeripheralEventMsg\x12(\n\x04kind\x18\x01 \x01(\x0e\x32\x1a.arhat.PeripheralEventType*4\n\x13PeripheralEventType\x12\x1d\n\x19_INVALID_PERIPHERAL_EVENT\x10\x00\x42!Z\x1f\x61rhat.dev/arhat-proto/arhatgopbb\x06proto3'
)

_PERIPHERALEVENTTYPE = _descriptor.EnumDescriptor(
  name='PeripheralEventType',
  full_name='arhat.PeripheralEventType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='_INVALID_PERIPHERAL_EVENT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=936,
  serialized_end=988,
)
_sym_db.RegisterEnumDescriptor(_PERIPHERALEVENTTYPE)

PeripheralEventType = enum_type_wrapper.EnumTypeWrapper(_PERIPHERALEVENTTYPE)
_INVALID_PERIPHERAL_EVENT = 0



_TLSCONFIG = _descriptor.Descriptor(
  name='TLSConfig',
  full_name='arhat.TLSConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_name', full_name='arhat.TLSConfig.server_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='insecure_skip_verify', full_name='arhat.TLSConfig.insecure_skip_verify', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_version', full_name='arhat.TLSConfig.min_version', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_version', full_name='arhat.TLSConfig.max_version', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ca_cert', full_name='arhat.TLSConfig.ca_cert', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cert', full_name='arhat.TLSConfig.cert', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='arhat.TLSConfig.key', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cipher_suites', full_name='arhat.TLSConfig.cipher_suites', index=7,
      number=8, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='next_protos', full_name='arhat.TLSConfig.next_protos', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=220,
)


_PERIPHERALCONNECTCMD_PARAMSENTRY = _descriptor.Descriptor(
  name='ParamsEntry',
  full_name='arhat.PeripheralConnectCmd.ParamsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='arhat.PeripheralConnectCmd.ParamsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='arhat.PeripheralConnectCmd.ParamsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=396,
)

_PERIPHERALCONNECTCMD = _descriptor.Descriptor(
  name='PeripheralConnectCmd',
  full_name='arhat.PeripheralConnectCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='arhat.PeripheralConnectCmd.target', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='arhat.PeripheralConnectCmd.params', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tls', full_name='arhat.PeripheralConnectCmd.tls', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PERIPHERALCONNECTCMD_PARAMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=396,
)


_PERIPHERALOPERATECMD_PARAMSENTRY = _descriptor.Descriptor(
  name='ParamsEntry',
  full_name='arhat.PeripheralOperateCmd.ParamsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='arhat.PeripheralOperateCmd.ParamsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='arhat.PeripheralOperateCmd.ParamsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=396,
)

_PERIPHERALOPERATECMD = _descriptor.Descriptor(
  name='PeripheralOperateCmd',
  full_name='arhat.PeripheralOperateCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='arhat.PeripheralOperateCmd.params', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='arhat.PeripheralOperateCmd.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PERIPHERALOPERATECMD_PARAMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=539,
)


_PERIPHERALMETRICSCOLLECTCMD_PARAMSENTRY = _descriptor.Descriptor(
  name='ParamsEntry',
  full_name='arhat.PeripheralMetricsCollectCmd.ParamsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='arhat.PeripheralMetricsCollectCmd.ParamsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='arhat.PeripheralMetricsCollectCmd.ParamsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=396,
)

_PERIPHERALMETRICSCOLLECTCMD = _descriptor.Descriptor(
  name='PeripheralMetricsCollectCmd',
  full_name='arhat.PeripheralMetricsCollectCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='arhat.PeripheralMetricsCollectCmd.params', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PERIPHERALMETRICSCOLLECTCMD_PARAMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=542,
  serialized_end=682,
)


_PERIPHERALCLOSECMD = _descriptor.Descriptor(
  name='PeripheralCloseCmd',
  full_name='arhat.PeripheralCloseCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=684,
  serialized_end=704,
)


_PERIPHERALOPERATIONRESULTMSG = _descriptor.Descriptor(
  name='PeripheralOperationResultMsg',
  full_name='arhat.PeripheralOperationResultMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='arhat.PeripheralOperationResultMsg.result', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=706,
  serialized_end=752,
)


_PERIPHERALMETRICSMSG_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='arhat.PeripheralMetricsMsg.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='arhat.PeripheralMetricsMsg.Value.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='arhat.PeripheralMetricsMsg.Value.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=829,
  serialized_end=870,
)

_PERIPHERALMETRICSMSG = _descriptor.Descriptor(
  name='PeripheralMetricsMsg',
  full_name='arhat.PeripheralMetricsMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='arhat.PeripheralMetricsMsg.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PERIPHERALMETRICSMSG_VALUE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=754,
  serialized_end=870,
)


_PERIPHERALEVENTMSG = _descriptor.Descriptor(
  name='PeripheralEventMsg',
  full_name='arhat.PeripheralEventMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kind', full_name='arhat.PeripheralEventMsg.kind', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=872,
  serialized_end=934,
)

_PERIPHERALCONNECTCMD_PARAMSENTRY.containing_type = _PERIPHERALCONNECTCMD
_PERIPHERALCONNECTCMD.fields_by_name['params'].message_type = _PERIPHERALCONNECTCMD_PARAMSENTRY
_PERIPHERALCONNECTCMD.fields_by_name['tls'].message_type = _TLSCONFIG
_PERIPHERALOPERATECMD_PARAMSENTRY.containing_type = _PERIPHERALOPERATECMD
_PERIPHERALOPERATECMD.fields_by_name['params'].message_type = _PERIPHERALOPERATECMD_PARAMSENTRY
_PERIPHERALMETRICSCOLLECTCMD_PARAMSENTRY.containing_type = _PERIPHERALMETRICSCOLLECTCMD
_PERIPHERALMETRICSCOLLECTCMD.fields_by_name['params'].message_type = _PERIPHERALMETRICSCOLLECTCMD_PARAMSENTRY
_PERIPHERALMETRICSMSG_VALUE.containing_type = _PERIPHERALMETRICSMSG
_PERIPHERALMETRICSMSG.fields_by_name['values'].message_type = _PERIPHERALMETRICSMSG_VALUE
_PERIPHERALEVENTMSG.fields_by_name['kind'].enum_type = _PERIPHERALEVENTTYPE
DESCRIPTOR.message_types_by_name['TLSConfig'] = _TLSCONFIG
DESCRIPTOR.message_types_by_name['PeripheralConnectCmd'] = _PERIPHERALCONNECTCMD
DESCRIPTOR.message_types_by_name['PeripheralOperateCmd'] = _PERIPHERALOPERATECMD
DESCRIPTOR.message_types_by_name['PeripheralMetricsCollectCmd'] = _PERIPHERALMETRICSCOLLECTCMD
DESCRIPTOR.message_types_by_name['PeripheralCloseCmd'] = _PERIPHERALCLOSECMD
DESCRIPTOR.message_types_by_name['PeripheralOperationResultMsg'] = _PERIPHERALOPERATIONRESULTMSG
DESCRIPTOR.message_types_by_name['PeripheralMetricsMsg'] = _PERIPHERALMETRICSMSG
DESCRIPTOR.message_types_by_name['PeripheralEventMsg'] = _PERIPHERALEVENTMSG
DESCRIPTOR.enum_types_by_name['PeripheralEventType'] = _PERIPHERALEVENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TLSConfig = _reflection.GeneratedProtocolMessageType('TLSConfig', (_message.Message,), {
  'DESCRIPTOR' : _TLSCONFIG,
  '__module__' : 'peripheral_pb2'
  # @@protoc_insertion_point(class_scope:arhat.TLSConfig)
  })
_sym_db.RegisterMessage(TLSConfig)

PeripheralConnectCmd = _reflection.GeneratedProtocolMessageType('PeripheralConnectCmd', (_message.Message,), {

  'ParamsEntry' : _reflection.GeneratedProtocolMessageType('ParamsEntry', (_message.Message,), {
    'DESCRIPTOR' : _PERIPHERALCONNECTCMD_PARAMSENTRY,
    '__module__' : 'peripheral_pb2'
    # @@protoc_insertion_point(class_scope:arhat.PeripheralConnectCmd.ParamsEntry)
    })
  ,
  'DESCRIPTOR' : _PERIPHERALCONNECTCMD,
  '__module__' : 'peripheral_pb2'
  # @@protoc_insertion_point(class_scope:arhat.PeripheralConnectCmd)
  })
_sym_db.RegisterMessage(PeripheralConnectCmd)
_sym_db.RegisterMessage(PeripheralConnectCmd.ParamsEntry)

PeripheralOperateCmd = _reflection.GeneratedProtocolMessageType('PeripheralOperateCmd', (_message.Message,), {

  'ParamsEntry' : _reflection.GeneratedProtocolMessageType('ParamsEntry', (_message.Message,), {
    'DESCRIPTOR' : _PERIPHERALOPERATECMD_PARAMSENTRY,
    '__module__' : 'peripheral_pb2'
    # @@protoc_insertion_point(class_scope:arhat.PeripheralOperateCmd.ParamsEntry)
    })
  ,
  'DESCRIPTOR' : _PERIPHERALOPERATECMD,
  '__module__' : 'peripheral_pb2'
  # @@protoc_insertion_point(class_scope:arhat.PeripheralOperateCmd)
  })
_sym_db.RegisterMessage(PeripheralOperateCmd)
_sym_db.RegisterMessage(PeripheralOperateCmd.ParamsEntry)

PeripheralMetricsCollectCmd = _reflection.GeneratedProtocolMessageType('PeripheralMetricsCollectCmd', (_message.Message,), {

  'ParamsEntry' : _reflection.GeneratedProtocolMessageType('ParamsEntry', (_message.Message,), {
    'DESCRIPTOR' : _PERIPHERALMETRICSCOLLECTCMD_PARAMSENTRY,
    '__module__' : 'peripheral_pb2'
    # @@protoc_insertion_point(class_scope:arhat.PeripheralMetricsCollectCmd.ParamsEntry)
    })
  ,
  'DESCRIPTOR' : _PERIPHERALMETRICSCOLLECTCMD,
  '__module__' : 'peripheral_pb2'
  # @@protoc_insertion_point(class_scope:arhat.PeripheralMetricsCollectCmd)
  })
_sym_db.RegisterMessage(PeripheralMetricsCollectCmd)
_sym_db.RegisterMessage(PeripheralMetricsCollectCmd.ParamsEntry)

PeripheralCloseCmd = _reflection.GeneratedProtocolMessageType('PeripheralCloseCmd', (_message.Message,), {
  'DESCRIPTOR' : _PERIPHERALCLOSECMD,
  '__module__' : 'peripheral_pb2'
  # @@protoc_insertion_point(class_scope:arhat.PeripheralCloseCmd)
  })
_sym_db.RegisterMessage(PeripheralCloseCmd)

PeripheralOperationResultMsg = _reflection.GeneratedProtocolMessageType('PeripheralOperationResultMsg', (_message.Message,), {
  'DESCRIPTOR' : _PERIPHERALOPERATIONRESULTMSG,
  '__module__' : 'peripheral_pb2'
  # @@protoc_insertion_point(class_scope:arhat.PeripheralOperationResultMsg)
  })
_sym_db.RegisterMessage(PeripheralOperationResultMsg)

PeripheralMetricsMsg = _reflection.GeneratedProtocolMessageType('PeripheralMetricsMsg', (_message.Message,), {

  'Value' : _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
    'DESCRIPTOR' : _PERIPHERALMETRICSMSG_VALUE,
    '__module__' : 'peripheral_pb2'
    # @@protoc_insertion_point(class_scope:arhat.PeripheralMetricsMsg.Value)
    })
  ,
  'DESCRIPTOR' : _PERIPHERALMETRICSMSG,
  '__module__' : 'peripheral_pb2'
  # @@protoc_insertion_point(class_scope:arhat.PeripheralMetricsMsg)
  })
_sym_db.RegisterMessage(PeripheralMetricsMsg)
_sym_db.RegisterMessage(PeripheralMetricsMsg.Value)

PeripheralEventMsg = _reflection.GeneratedProtocolMessageType('PeripheralEventMsg', (_message.Message,), {
  'DESCRIPTOR' : _PERIPHERALEVENTMSG,
  '__module__' : 'peripheral_pb2'
  # @@protoc_insertion_point(class_scope:arhat.PeripheralEventMsg)
  })
_sym_db.RegisterMessage(PeripheralEventMsg)


DESCRIPTOR._options = None
_PERIPHERALCONNECTCMD_PARAMSENTRY._options = None
_PERIPHERALOPERATECMD_PARAMSENTRY._options = None
_PERIPHERALMETRICSCOLLECTCMD_PARAMSENTRY._options = None
# @@protoc_insertion_point(module_scope)
