/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_ARHAT_DEVICE_GRPC_PB_H_INCLUDED
#define PB_ARHAT_DEVICE_GRPC_PB_H_INCLUDED
#include <pb.h>
#include "device.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
