/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.4 */

#ifndef PB_ARHAT_PERIPHERAL_PB_H_INCLUDED
#define PB_ARHAT_PERIPHERAL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _arhat_PeripheralEventType {
    arhat_PeripheralEventType__INVALID_PERIPHERAL_EVENT = 0
} arhat_PeripheralEventType;

/* Struct definitions */
typedef struct _arhat_PeripheralCloseCmd {
    char dummy_field;
} arhat_PeripheralCloseCmd;

typedef struct _arhat_PeripheralConnectCmd_ParamsEntry {
    pb_callback_t key;
    pb_callback_t value;
} arhat_PeripheralConnectCmd_ParamsEntry;

typedef struct _arhat_PeripheralMetricsCollectCmd {
    pb_callback_t params;
} arhat_PeripheralMetricsCollectCmd;

typedef struct _arhat_PeripheralMetricsCollectCmd_ParamsEntry {
    pb_callback_t key;
    pb_callback_t value;
} arhat_PeripheralMetricsCollectCmd_ParamsEntry;

typedef struct _arhat_PeripheralMetricsMsg {
    pb_callback_t values;
} arhat_PeripheralMetricsMsg;

typedef struct _arhat_PeripheralOperateCmd {
    pb_callback_t params;
    pb_callback_t data;
} arhat_PeripheralOperateCmd;

typedef struct _arhat_PeripheralOperateCmd_ParamsEntry {
    pb_callback_t key;
    pb_callback_t value;
} arhat_PeripheralOperateCmd_ParamsEntry;

typedef struct _arhat_PeripheralOperationResultMsg {
    pb_callback_t result;
} arhat_PeripheralOperationResultMsg;

typedef struct _arhat_PeripheralEventMsg {
    arhat_PeripheralEventType kind;
} arhat_PeripheralEventMsg;

typedef struct _arhat_PeripheralMetricsMsg_Value {
    double value;
    int64_t timestamp;
} arhat_PeripheralMetricsMsg_Value;

typedef struct _arhat_TLSConfig {
    pb_callback_t server_name;
    bool insecure_skip_verify;
    uint32_t min_version;
    uint32_t max_version;
    pb_callback_t ca_cert;
    pb_callback_t cert;
    pb_callback_t key;
    pb_callback_t cipher_suites;
    pb_callback_t next_protos;
} arhat_TLSConfig;

typedef struct _arhat_PeripheralConnectCmd {
    pb_callback_t target;
    pb_callback_t params;
    bool has_tls;
    arhat_TLSConfig tls;
} arhat_PeripheralConnectCmd;


/* Helper constants for enums */
#define _arhat_PeripheralEventType_MIN arhat_PeripheralEventType__INVALID_PERIPHERAL_EVENT
#define _arhat_PeripheralEventType_MAX arhat_PeripheralEventType__INVALID_PERIPHERAL_EVENT
#define _arhat_PeripheralEventType_ARRAYSIZE ((arhat_PeripheralEventType)(arhat_PeripheralEventType__INVALID_PERIPHERAL_EVENT+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define arhat_TLSConfig_init_default             {{{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define arhat_PeripheralConnectCmd_init_default  {{{NULL}, NULL}, {{NULL}, NULL}, false, arhat_TLSConfig_init_default}
#define arhat_PeripheralConnectCmd_ParamsEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define arhat_PeripheralOperateCmd_init_default  {{{NULL}, NULL}, {{NULL}, NULL}}
#define arhat_PeripheralOperateCmd_ParamsEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define arhat_PeripheralMetricsCollectCmd_init_default {{{NULL}, NULL}}
#define arhat_PeripheralMetricsCollectCmd_ParamsEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define arhat_PeripheralCloseCmd_init_default    {0}
#define arhat_PeripheralOperationResultMsg_init_default {{{NULL}, NULL}}
#define arhat_PeripheralMetricsMsg_init_default  {{{NULL}, NULL}}
#define arhat_PeripheralMetricsMsg_Value_init_default {0, 0}
#define arhat_PeripheralEventMsg_init_default    {_arhat_PeripheralEventType_MIN}
#define arhat_TLSConfig_init_zero                {{{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define arhat_PeripheralConnectCmd_init_zero     {{{NULL}, NULL}, {{NULL}, NULL}, false, arhat_TLSConfig_init_zero}
#define arhat_PeripheralConnectCmd_ParamsEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define arhat_PeripheralOperateCmd_init_zero     {{{NULL}, NULL}, {{NULL}, NULL}}
#define arhat_PeripheralOperateCmd_ParamsEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define arhat_PeripheralMetricsCollectCmd_init_zero {{{NULL}, NULL}}
#define arhat_PeripheralMetricsCollectCmd_ParamsEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define arhat_PeripheralCloseCmd_init_zero       {0}
#define arhat_PeripheralOperationResultMsg_init_zero {{{NULL}, NULL}}
#define arhat_PeripheralMetricsMsg_init_zero     {{{NULL}, NULL}}
#define arhat_PeripheralMetricsMsg_Value_init_zero {0, 0}
#define arhat_PeripheralEventMsg_init_zero       {_arhat_PeripheralEventType_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define arhat_PeripheralConnectCmd_ParamsEntry_key_tag 1
#define arhat_PeripheralConnectCmd_ParamsEntry_value_tag 2
#define arhat_PeripheralMetricsCollectCmd_params_tag 1
#define arhat_PeripheralMetricsCollectCmd_ParamsEntry_key_tag 1
#define arhat_PeripheralMetricsCollectCmd_ParamsEntry_value_tag 2
#define arhat_PeripheralMetricsMsg_values_tag    1
#define arhat_PeripheralOperateCmd_params_tag    1
#define arhat_PeripheralOperateCmd_data_tag      2
#define arhat_PeripheralOperateCmd_ParamsEntry_key_tag 1
#define arhat_PeripheralOperateCmd_ParamsEntry_value_tag 2
#define arhat_PeripheralOperationResultMsg_result_tag 1
#define arhat_PeripheralEventMsg_kind_tag        1
#define arhat_PeripheralMetricsMsg_Value_value_tag 1
#define arhat_PeripheralMetricsMsg_Value_timestamp_tag 2
#define arhat_TLSConfig_server_name_tag          1
#define arhat_TLSConfig_insecure_skip_verify_tag 2
#define arhat_TLSConfig_min_version_tag          3
#define arhat_TLSConfig_max_version_tag          4
#define arhat_TLSConfig_ca_cert_tag              5
#define arhat_TLSConfig_cert_tag                 6
#define arhat_TLSConfig_key_tag                  7
#define arhat_TLSConfig_cipher_suites_tag        8
#define arhat_TLSConfig_next_protos_tag          9
#define arhat_PeripheralConnectCmd_target_tag    1
#define arhat_PeripheralConnectCmd_params_tag    2
#define arhat_PeripheralConnectCmd_tls_tag       3

/* Struct field encoding specification for nanopb */
#define arhat_TLSConfig_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   server_name,       1) \
X(a, STATIC,   SINGULAR, BOOL,     insecure_skip_verify,   2) \
X(a, STATIC,   SINGULAR, UINT32,   min_version,       3) \
X(a, STATIC,   SINGULAR, UINT32,   max_version,       4) \
X(a, CALLBACK, SINGULAR, BYTES,    ca_cert,           5) \
X(a, CALLBACK, SINGULAR, BYTES,    cert,              6) \
X(a, CALLBACK, SINGULAR, BYTES,    key,               7) \
X(a, CALLBACK, REPEATED, UINT32,   cipher_suites,     8) \
X(a, CALLBACK, REPEATED, STRING,   next_protos,       9)
#define arhat_TLSConfig_CALLBACK pb_default_field_callback
#define arhat_TLSConfig_DEFAULT NULL

#define arhat_PeripheralConnectCmd_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   target,            1) \
X(a, CALLBACK, REPEATED, MESSAGE,  params,            2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  tls,               3)
#define arhat_PeripheralConnectCmd_CALLBACK pb_default_field_callback
#define arhat_PeripheralConnectCmd_DEFAULT NULL
#define arhat_PeripheralConnectCmd_params_MSGTYPE arhat_PeripheralConnectCmd_ParamsEntry
#define arhat_PeripheralConnectCmd_tls_MSGTYPE arhat_TLSConfig

#define arhat_PeripheralConnectCmd_ParamsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define arhat_PeripheralConnectCmd_ParamsEntry_CALLBACK pb_default_field_callback
#define arhat_PeripheralConnectCmd_ParamsEntry_DEFAULT NULL

#define arhat_PeripheralOperateCmd_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  params,            1) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              2)
#define arhat_PeripheralOperateCmd_CALLBACK pb_default_field_callback
#define arhat_PeripheralOperateCmd_DEFAULT NULL
#define arhat_PeripheralOperateCmd_params_MSGTYPE arhat_PeripheralOperateCmd_ParamsEntry

#define arhat_PeripheralOperateCmd_ParamsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define arhat_PeripheralOperateCmd_ParamsEntry_CALLBACK pb_default_field_callback
#define arhat_PeripheralOperateCmd_ParamsEntry_DEFAULT NULL

#define arhat_PeripheralMetricsCollectCmd_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  params,            1)
#define arhat_PeripheralMetricsCollectCmd_CALLBACK pb_default_field_callback
#define arhat_PeripheralMetricsCollectCmd_DEFAULT NULL
#define arhat_PeripheralMetricsCollectCmd_params_MSGTYPE arhat_PeripheralMetricsCollectCmd_ParamsEntry

#define arhat_PeripheralMetricsCollectCmd_ParamsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define arhat_PeripheralMetricsCollectCmd_ParamsEntry_CALLBACK pb_default_field_callback
#define arhat_PeripheralMetricsCollectCmd_ParamsEntry_DEFAULT NULL

#define arhat_PeripheralCloseCmd_FIELDLIST(X, a) \

#define arhat_PeripheralCloseCmd_CALLBACK NULL
#define arhat_PeripheralCloseCmd_DEFAULT NULL

#define arhat_PeripheralOperationResultMsg_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, BYTES,    result,            1)
#define arhat_PeripheralOperationResultMsg_CALLBACK pb_default_field_callback
#define arhat_PeripheralOperationResultMsg_DEFAULT NULL

#define arhat_PeripheralMetricsMsg_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  values,            1)
#define arhat_PeripheralMetricsMsg_CALLBACK pb_default_field_callback
#define arhat_PeripheralMetricsMsg_DEFAULT NULL
#define arhat_PeripheralMetricsMsg_values_MSGTYPE arhat_PeripheralMetricsMsg_Value

#define arhat_PeripheralMetricsMsg_Value_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   value,             1) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         2)
#define arhat_PeripheralMetricsMsg_Value_CALLBACK NULL
#define arhat_PeripheralMetricsMsg_Value_DEFAULT NULL

#define arhat_PeripheralEventMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    kind,              1)
#define arhat_PeripheralEventMsg_CALLBACK NULL
#define arhat_PeripheralEventMsg_DEFAULT NULL

extern const pb_msgdesc_t arhat_TLSConfig_msg;
extern const pb_msgdesc_t arhat_PeripheralConnectCmd_msg;
extern const pb_msgdesc_t arhat_PeripheralConnectCmd_ParamsEntry_msg;
extern const pb_msgdesc_t arhat_PeripheralOperateCmd_msg;
extern const pb_msgdesc_t arhat_PeripheralOperateCmd_ParamsEntry_msg;
extern const pb_msgdesc_t arhat_PeripheralMetricsCollectCmd_msg;
extern const pb_msgdesc_t arhat_PeripheralMetricsCollectCmd_ParamsEntry_msg;
extern const pb_msgdesc_t arhat_PeripheralCloseCmd_msg;
extern const pb_msgdesc_t arhat_PeripheralOperationResultMsg_msg;
extern const pb_msgdesc_t arhat_PeripheralMetricsMsg_msg;
extern const pb_msgdesc_t arhat_PeripheralMetricsMsg_Value_msg;
extern const pb_msgdesc_t arhat_PeripheralEventMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define arhat_TLSConfig_fields &arhat_TLSConfig_msg
#define arhat_PeripheralConnectCmd_fields &arhat_PeripheralConnectCmd_msg
#define arhat_PeripheralConnectCmd_ParamsEntry_fields &arhat_PeripheralConnectCmd_ParamsEntry_msg
#define arhat_PeripheralOperateCmd_fields &arhat_PeripheralOperateCmd_msg
#define arhat_PeripheralOperateCmd_ParamsEntry_fields &arhat_PeripheralOperateCmd_ParamsEntry_msg
#define arhat_PeripheralMetricsCollectCmd_fields &arhat_PeripheralMetricsCollectCmd_msg
#define arhat_PeripheralMetricsCollectCmd_ParamsEntry_fields &arhat_PeripheralMetricsCollectCmd_ParamsEntry_msg
#define arhat_PeripheralCloseCmd_fields &arhat_PeripheralCloseCmd_msg
#define arhat_PeripheralOperationResultMsg_fields &arhat_PeripheralOperationResultMsg_msg
#define arhat_PeripheralMetricsMsg_fields &arhat_PeripheralMetricsMsg_msg
#define arhat_PeripheralMetricsMsg_Value_fields &arhat_PeripheralMetricsMsg_Value_msg
#define arhat_PeripheralEventMsg_fields &arhat_PeripheralEventMsg_msg

/* Maximum encoded size of messages (where known) */
/* arhat_TLSConfig_size depends on runtime parameters */
/* arhat_PeripheralConnectCmd_size depends on runtime parameters */
/* arhat_PeripheralConnectCmd_ParamsEntry_size depends on runtime parameters */
/* arhat_PeripheralOperateCmd_size depends on runtime parameters */
/* arhat_PeripheralOperateCmd_ParamsEntry_size depends on runtime parameters */
/* arhat_PeripheralMetricsCollectCmd_size depends on runtime parameters */
/* arhat_PeripheralMetricsCollectCmd_ParamsEntry_size depends on runtime parameters */
#define arhat_PeripheralCloseCmd_size            0
/* arhat_PeripheralOperationResultMsg_size depends on runtime parameters */
/* arhat_PeripheralMetricsMsg_size depends on runtime parameters */
#define arhat_PeripheralMetricsMsg_Value_size    20
#define arhat_PeripheralEventMsg_size            2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
