/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "peripheral.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(arhat_TLSConfig, arhat_TLSConfig, AUTO)


PB_BIND(arhat_PeripheralConnectCmd, arhat_PeripheralConnectCmd, AUTO)


PB_BIND(arhat_PeripheralConnectCmd_ParamsEntry, arhat_PeripheralConnectCmd_ParamsEntry, AUTO)


PB_BIND(arhat_PeripheralOperateCmd, arhat_PeripheralOperateCmd, AUTO)


PB_BIND(arhat_PeripheralOperateCmd_ParamsEntry, arhat_PeripheralOperateCmd_ParamsEntry, AUTO)


PB_BIND(arhat_PeripheralMetricsCollectCmd, arhat_PeripheralMetricsCollectCmd, AUTO)


PB_BIND(arhat_PeripheralMetricsCollectCmd_ParamsEntry, arhat_PeripheralMetricsCollectCmd_ParamsEntry, AUTO)


PB_BIND(arhat_PeripheralCloseCmd, arhat_PeripheralCloseCmd, AUTO)


PB_BIND(arhat_PeripheralOperationResultMsg, arhat_PeripheralOperationResultMsg, AUTO)


PB_BIND(arhat_PeripheralMetricsMsg, arhat_PeripheralMetricsMsg, AUTO)


PB_BIND(arhat_PeripheralMetricsMsg_Value, arhat_PeripheralMetricsMsg_Value, AUTO)


PB_BIND(arhat_PeripheralEventMsg, arhat_PeripheralEventMsg, AUTO)




#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

