/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "proto.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(arhat_Cmd, arhat_Cmd, AUTO)


PB_BIND(arhat_SessionSetCmd, arhat_SessionSetCmd, AUTO)


PB_BIND(arhat_Msg, arhat_Msg, AUTO)


PB_BIND(arhat_DoneMsg, arhat_DoneMsg, AUTO)


PB_BIND(arhat_ErrorMsg, arhat_ErrorMsg, AUTO)


PB_BIND(arhat_RegisterMsg, arhat_RegisterMsg, AUTO)





